### ISSUE TITLE
short read star align rule (3a) doesn't obey thread # assigned by config file

### ISSUE THREAD

**Issue by whitma** [mckellardw/slide_snake#8]
8 cores were designated in the config file, but when rule 3a started running, it did so using 24 cores. 

[snakefiles.zip](https://github.com/user-attachments/files/18042452/snakefiles.zip)

**Comment by mckellardw** [comment]
Could you share what you ran from the command line to launch the pipeline, and the log output by snakemake? And are you running the pipeline locally or with slurm? Thanks!

And just to clarify, I assume you mean rule `ilmn_3a_STARsolo_firstPass`?

**Comment by whitma** [comment]
Of course! I am now realizing what `-j 56` is instructing... but yes run locally using the example command line from the readme.md. 

`snakemake -k -p --use-conda --conda-frontend mamba -j 56`

And yes, rule `ilmn_3a_STARsolo_firstPass`.

**Comment by mckellardw** [comment]
Can you check what version of snakemake you are using? If you are using v8, as specified in `slide_snake/envs/slsn.yml`, then it is likely using the "default" snakemake profile when run locally. You can specify resource usage for each rule in `slide_snake/profiles/default/config.yaml`

So you should be able to just change the value for "  ilmn_3a_STARsolo_firstPass" under the "set-threads" section (line 19 in the current version) to whatever best suits your needs.

The `threads: config["CORES"]` is a leftover from older versions of snakemake, before profiles were introduced.

**Comment by whitma** [comment]
snakemake v8.16.0 per `slide_snake/envs/slsn.yml` 

Thanks! I can confirm that the value for ilmn_3a_STARsolo_firstpass is 24 in `slide_snake/profiles/default/config.yaml`, and will update these accordingly next time. 

If run with slurm, will the same thing happen with `slide_snake/profiles/slurm/config.yaml`?

**Comment by mckellardw** [comment]
Yes! Be sure to update the values in that config file to your setup (`slurm_partition` and `slurm_account`) before running, or you will get an error.
